django/CRM/CRM/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from .views import home

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version="v1",
        description="API documentation",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cars.urls")),
    path("", include("customer.urls")),
    path("", include("branches.urls")),
    path("", include("rents.urls")),
    path("", home, name="home"),
    # API
    path("api/v1/", include("cars.api.urls")),
    path("api/v1/", include("customer.api.urls")),
    path("api/v1/", include("branches.api.urls")),
    path("api/v1/", include("rents.api.urls")),
    path("api/v1/", include("CRM.api.urls")),
    # Swagger
    path(
        "api/v1/swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "api/v1/redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    # REST
    path("api/v1/auth/", include("rest_framework.urls")),
    path("api/v1/auth/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path(
        "api/v1/auth/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"
    ),
    path("api/v1/auth/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]

django/CRM/cars/api/urls.py
from django.urls import include, path
from rest_framework import routers

from cars.api.viewsets import CarViewSet

router = routers.DefaultRouter()
router.register(r"cars", CarViewSet)

urlpatterns = [
    path("", include(router.urls)),
]

django/CRM/cars/urls.py
from django.urls import path

from .views import (create_car, delete_car_by_id, edit_car_by_id,
                    get_car_by_id, list_cars)

urlpatterns = [
    path("cars/", list_cars, name="list_cars"),
    path("cars/<int:car_id>/", get_car_by_id, name="get_car_by_id"),
    path("cars/<int:car_id>/delete", delete_car_by_id, name="delete_car_by_id"),
    path("cars/create/", create_car, name="create_car"),
    path("cars/<int:car_id>/edit", edit_car_by_id, name="edit_car_by_id"),
]

django/CRM/cars/models.py
from django.db import models

from branches.models import Branch


# Create your models here.
class Car(models.Model):
    AVAILABLE = 1
    UNAVAILABLE = 2

    STATUS_CHOICES = (
        (AVAILABLE, "Available"),
        (UNAVAILABLE, "Unavailable"),
    )

    def create_filename(self, filename):
        return f"cars/{self.brand}-{self.model}-{self.year}-{self.plate}"

    model = models.CharField(max_length=100, null=True)
    brand = models.CharField(max_length=100, null=True)
    year = models.IntegerField(null=True)
    color = models.CharField(max_length=100, null=True)
    plate = models.CharField(max_length=8, null=True, unique=True)
    chassis_type = models.CharField(max_length=20, null=True)
    status = models.PositiveSmallIntegerField(
        null=True, default=1, choices=STATUS_CHOICES
    )
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to=create_filename, null=True)

    def __str__(self):
        return self.plate

    class Meta:
        verbose_name_plural = "Cars"

django/CRM/cars/forms.py
from django import forms
from django.core.validators import RegexValidator

from .models import Car


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = "__all__"
        widgets = {
            "model": forms.TextInput(attrs={"class": "input input-bordered w-full max-w-xs"}),
            "brand": forms.TextInput(attrs={"class": "input input-bordered w-full max-w-xs"}),
            "year": forms.NumberInput(attrs={"class": "input input-bordered w-full max-w-xs"}),
            "color": forms.TextInput(attrs={"class": "input input-bordered w-full max-w-xs"}),
            "plate": forms.TextInput(attrs={"class": "input input-bordered w-full max-w-xs"}),
            "chassis_type": forms.TextInput(attrs={"class": "input input-bordered w-full max-w-xs"}),
            "image": forms.FileInput(attrs={"class": "input input-bordered w-full max-w-xs"}),
        }
        labels = {
            "model": "Model",
            "brand": "Brand",
            "year": "Year",
            "color": "Color",
            "plate": "Plate",
            "chassis_type": "Chassis Type",
            "image": "Image",
        }
        error_messages = {
            "year": {"invalid": "Year must be between 1900 and 2100."},
            "plate": {
                "invalid": "Plate must be with format AAA9999, AAAA999, AAA-9999 or AAAA-999."
            },
        }

    def clean_year(self):
        year = self.cleaned_data.get("year")
        if not 1900 <= year <= 2100:
            raise forms.ValidationError("Year must be between 1900 and 2100.")
        return year

    def save_car(self):
        plate = self.cleaned_data["plate"].replace("-", "")
        car = Car(
            plate=plate.upper(),
            model=self.cleaned_data["model"],
            brand=self.cleaned_data["brand"],
            year=self.cleaned_data["year"],
            color=self.cleaned_data["color"],
            chassis_type=self.cleaned_data["chassis_type"],
            branch=self.cleaned_data["branch"],
        )
        image_file = self.cleaned_data["image"]
        if image_file:
            car.image.save(image_file.name, image_file)
        car.save()

    def update_car(self, car):
        plate = self.cleaned_data["plate"].replace("-", "")
        car.plate = plate.upper()
        car.model = self.cleaned_data["model"]
        car.brand = self.cleaned_data["brand"]
        car.year = self.cleaned_data["year"]
        car.color = self.cleaned_data["color"]
        car.chassis_type = self.cleaned_data["chassis_type"]
        car.branch = self.cleaned_data["branch"]
        car.save()

django/CRM/cars/views.py
import uuid
import boto3
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import redirect, render

from CRM.settings import (AWS_ACCESS_KEY_ID, AWS_S3_REGION_NAME,
                          AWS_SECRET_ACCESS_KEY, SQS_QUEUE_URL)

from .forms import CarForm
from .models import Car

sqs = boto3.client(
    "sqs",
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=AWS_S3_REGION_NAME,
)


def list_cars(request):
    cars = Car.objects.all()
    messages = retrieve_sqs_messages()
    return render(request, "list_cars.html", {"cars": cars, "messages": messages})

def create_car(request):
    if request.method == "POST":
        form = CarForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save_car()

                message_body = f"Car {form.cleaned_data['plate']} created"
                send_sqs_message(message_body, form.cleaned_data["plate"])

                return redirect("list_cars")

            except IntegrityError:
                return render(
                    request,
                    "create_car.html",
                    {"form": form, "error_message": "Plate already exists"},
                )

    else:
        form = CarForm()

    return render(request, "create_car.html", {"form": form})

def retrieve_sqs_messages():
    response = sqs.receive_message(
        QueueUrl=SQS_QUEUE_URL,
        MaxNumberOfMessages=10,
        AttributeNames=['MessageGroupId', 'MessageDeduplicationId'],
        MessageAttributeNames=['All']
    )


    messages = []
    if "Messages" in response:
        for message in response["Messages"]:
            (message["Attributes"])
            message_body = message["Body"]
            message_group_id = message["Attributes"]["MessageGroupId"]
            message_deduplication_id = message["Attributes"]["MessageDeduplicationId"]
            messages.append(message_body)
            delete_sqs_message(message["ReceiptHandle"])

    return messages


def send_sqs_message(message_body, message_group_id):
    sqs.send_message(
        QueueUrl=SQS_QUEUE_URL,
        MessageBody=message_body,
        MessageGroupId=message_group_id,
        MessageDeduplicationId=str(uuid.uuid4()),
    )


def delete_sqs_message(receipt_handle):
    sqs.delete_message(
        QueueUrl=SQS_QUEUE_URL,
        ReceiptHandle=receipt_handle,
    )


def get_car_by_id(request, car_id):
    try:
        car = Car.objects.get(id=car_id)
        return render(request, "car_by_id.html", {"car": car})

    except Car.DoesNotExist:
        return HttpResponse("Car not found")


def edit_car_by_id(request, car_id):
    try:
        car = Car.objects.get(id=car_id)
        if request.method == "POST":
            form = CarForm(request.POST, instance=car)
            if form.is_valid():
                form.update_car(car=car)
                return redirect("list_cars")

        else:
            form = CarForm(instance=car)

        return render(request, "edit_car.html", {"form": form, "car": car})

    except Car.DoesNotExist:
        return HttpResponse("Car not found")


def delete_car_by_id(request, car_id):
    try:
        car = Car.objects.get(id=car_id)
        car.delete()
        return redirect("list_cars")

    except Car.DoesNotExist:
        return HttpResponse("Car not found")

django/CRM/cars/templates/base.html
<!DOCTYPE html>
<html data-theme="pastel">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Tailwind and DaisyUI CDN -->
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.51.6/dist/full.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %}Renter{% endblock %}</title>
  </head>

  <body>
    {% include 'header.html' %}
    <!-- Conteúdo específico de cada página -->
    {% block content %} {% endblock %}
    <!-- Scripts comuns -->
  </body>
</html>

django/CRM/cars/templates/car_by_id.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Car Info {% endblock %}


{% block content %}

<div class="min-h-screen flex flex-col gap-6 justify-center items-center">
    <h1 class="text-3xl font-semibold">Car Info</h1>

    <div class="flex flex-col gap-4 p-6 card shadow-2xl w-[400px]">

        <div class="flex flex-col gap-2">
            <p class="uppercase font-medium">Model: <span class="font-normal capitalize">{{ car.model }}</span></p>
            <p class="uppercase font-medium">Brand: <span class="font-normal capitalize">{{ car.brand }}</span></p>
            <p class="uppercase font-medium">Color: <span class="font-normal capitalize">{{ car.color }}</span></p>
            <p class="uppercase font-medium">Plate: <span class="font-normal capitalize">{{ car.plate }}</span></p>
            <p class="uppercase font-medium">Year: <span class="font-normal capitalize">{{ car.year }}</span></p>
            <p class="uppercase font-medium">Status: <span class="font-normal capitalize">
                    {{ car.get_status_display}}</span></p>
            <p class="uppercase font-medium">Chassis Type: <span class="font-normal capitalize">
                    {{ car.chassis_type}}</span></p>
            <p class="uppercase font-medium">Branch CNPJ: <span class="font-normal capitalize">
                    {{ car.branch.cnpj }}</span></p>
            <p class="uppercase font-medium">Image:
                <img src="{{ car.image.url }}" alt="{{ car.model }}"
                    class="w-full h-[200px] object-cover object-center rounded-lg">
            </p>

        </div>

        <div>
            <a href="{%url 'edit_car_by_id' car_id=car.id%}" class="btn gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#e0e0e0" viewBox="0 0 256 256">
                    <path
                        d="M227.31,73.37,182.63,28.68a16,16,0,0,0-22.63,0L36.69,152A15.86,15.86,0,0,0,32,163.31V208a16,16,0,0,0,16,16H92.69A15.86,15.86,0,0,0,104,219.31L227.31,96a16,16,0,0,0,0-22.63ZM92.69,208H48V163.31l88-88L180.69,120ZM192,108.68,147.31,64l24-24L216,84.68Z">
                    </path>
                </svg>
                Edit
            </a>
            <a href="{%url 'delete_car_by_id' car_id=car.id %}" class="btn gap-2 btn-error text-white" title="Remove">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#e0e0e0" viewBox="0 0 256 256">
                    <path
                        d="M216,48H40a8,8,0,0,0,0,16h8V208a16,16,0,0,0,16,16H192a16,16,0,0,0,16-16V64h8a8,8,0,0,0,0-16ZM192,208H64V64H192ZM80,24a8,8,0,0,1,8-8h80a8,8,0,0,1,0,16H88A8,8,0,0,1,80,24Z">
                    </path>
                </svg>
                Remove
            </a>
        </div>
    </div>
</div>

{% endblock %}

django/CRM/cars/templates/create_car.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Insert a new car {% endblock %}


{% block content %}

<style>
    .errorlist {
        color: red;
        font-size: small;
    }
</style>

<div class="flex flex-col justify-center items-center gap-4 p-8">
    <h1 class="text-2xl">Insert a new car</h1>


    <form method="POST" enctype="multipart/form-data" class="form-control max-w-xs w-full  flex flex-col gap-2">
        {% csrf_token %}

        {{ form.as_p }}
        <button class="btn">Create</button>
    </form>

</div>

{% endblock %}

django/CRM/cars/templates/edit_car.html
<p>Editing car info for plate: {{ car.plate }}</p>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

django/CRM/cars/templates/header.html
<div class="navbar bg-base-100 shadow">

    <div class="navbar-start">
        <div class="dropdown">
            <label tabindex="0" class="btn btn-ghost lg:hidden">

                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
                </svg>

            </label>

            <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
                <li tabindex="0">
                    <a>
                        Cars
                        <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                            viewBox="0 0 24 24">
                            <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
                        </svg>
                    </a>

                    <ul class="p-2 bg-base-100 shadow-md z-50">
                        <li><a href="/cars/">List</a></li>
                        <li><a href="/cars/create/">Create</a></li>
                    </ul>
                </li>

                <li tabindex="1">
                    <a>
                        Customers
                        <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                            viewBox="0 0 24 24">
                            <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
                        </svg>
                    </a>

                    <ul class="p-2 bg-base-100 shadow-md z-50">
                        <li><a href="/customers/">List</a></li>
                        <li><a href="/customers/create/">Create</a></li>
                    </ul>
                </li>

                <li tabindex="2">
                    <a>
                        Branches
                        <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                            viewBox="0 0 24 24">
                            <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
                        </svg>
                    </a>

                    <ul class="p-2 bg-base-100 shadow-md z-50">
                        <li><a href="/branches/">List</a></li>
                        <li><a href="/branches/create/">Create</a></li>
                    </ul>
                </li>

                <li tabindex="3">
                    <a>
                        Rents
                        <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                            viewBox="0 0 24 24">
                            <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
                        </svg>
                    </a>

                    <ul class="p-2 bg-base-100 shadow-md z-50">
                        <li><a href="/rents/">List</a></li>
                        <li><a href="/rents/create/">Create</a></li>
                    </ul>
                </li>
            </ul>
        </div>

        <a class="btn btn-ghost normal-case text-xl" href="/">Renter</a>
    </div>

    <div class="navbar-center hidden lg:flex">

        <ul class="menu menu-horizontal px-1">
            <li tabindex="0">
                <a>
                    Cars
                    <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                        viewBox="0 0 24 24">
                        <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
                    </svg>
                </a>

                <ul class="p-2 bg-base-100 shadow-md z-50">
                    <li><a href="/cars/">List</a></li>
                    <li><a href="/cars/create/">Create</a></li>
                </ul>
            </li>

            <li tabindex="1">
                <a>
                    Customers
                    <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                        viewBox="0 0 24 24">
                        <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
                    </svg>
                </a>

                <ul class="p-2 bg-base-100 shadow-md z-50">
                    <li><a href="/customers/">List</a></li>
                    <li><a href="/customers/create/">Create</a></li>
                </ul>
            </li>

            <li tabindex="2">
                <a>
                    Branches
                    <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                        viewBox="0 0 24 24">
                        <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
                    </svg>
                </a>

                <ul class="p-2 bg-base-100 shadow-md z-50">
                    <li><a href="/branches/">List</a></li>
                    <li><a href="/branches/create/">Create</a></li>
                </ul>
            </li>

            <li tabindex="3">
                <a>
                    Rents
                    <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                        viewBox="0 0 24 24">
                        <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
                    </svg>
                </a>

                <ul class="p-2 bg-base-100 shadow-md z-50">
                    <li><a href="/rents/">List</a></li>
                    <li><a href="/rents/create/">Create</a></li>
                </ul>
            </li>
        </ul>
    </div>

    <div class="navbar-end">

    </div>
</div>

django/CRM/cars/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Car Info {% endblock %}


{% block content %}

<div class="min-h-screen flex flex-col gap-6 justify-center items-center">
    <h1 class="text-3xl font-semibold">Car Info</h1>

    <div class="flex flex-col gap-4 p-6 card shadow-2xl w-[400px]">

        <div class="flex flex-col gap-2">
            <p class="uppercase font-medium">Model: <span class="font-normal capitalize">{{ car.model }}</span></p>
            <p class="uppercase font-medium">Brand: <span class="font-normal capitalize">{{ car.brand }}</span></p>
            <p class="uppercase font-medium">Color: <span class="font-normal capitalize">{{ car.color }}</span></p>
            <p class="uppercase font-medium">Plate: <span class="font-normal capitalize">{{ car.plate }}</span></p>
            <p class="uppercase font-medium">Year: <span class="font-normal capitalize">{{ car.year }}</span></p>
            <p class="uppercase font-medium">Chassis Type: <span class="font-normal capitalize">
                    {{ car.chassis_type}}</span></p>
        </div>

        <div>
            <a href="{%url 'edit_car_by_id' car_id=car.id%}" class="btn gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#e0e0e0" viewBox="0 0 256 256">
                    <path
                        d="M227.31,73.37,182.63,28.68a16,16,0,0,0-22.63,0L36.69,152A15.86,15.86,0,0,0,32,163.31V208a16,16,0,0,0,16,16H92.69A15.86,15.86,0,0,0,104,219.31L227.31,96a16,16,0,0,0,0-22.63ZM92.69,208H48V163.31l88-88L180.69,120ZM192,108.68,147.31,64l24-24L216,84.68Z">
                    </path>
                </svg>
                Edit
            </a>
            <a href="{%url 'delete_car_by_id' car_id=car.id %}" class="btn gap-2 text-base-100 btn-error"
                title="Remove">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#e0e0e0" viewBox="0 0 256 256">
                    <path
                        d="M216,48H40a8,8,0,0,0,0,16h8V208a16,16,0,0,0,16,16H192a16,16,0,0,0,16-16V64h8a8,8,0,0,0,0-16ZM192,208H64V64H192ZM80,24a8,8,0,0,1,8-8h80a8,8,0,0,1,0,16H88A8,8,0,0,1,80,24Z">
                    </path>
                </svg>
                Remove
            </a>
        </div>
    </div>
</div>

{% endblock %}

django/CRM/cars/templates/list_cars.html
{% extends 'base.html' %} {% load static %} {% block title %} List all cars {% endblock %} {% block content %}

<div class="flex flex-col gap-4 p-8">
  <h1 class="text-2xl">Car List</h1>
  {% if messages %} {% for message in messages %}
  <div class="alert alert-success" role="alert">{{ message }}</div>
  {% endfor %} {% endif %}

  <div class="overflow-x-auto">
    <table class="table table-zebra w-full shadow">
      <thead>
        <tr>
          <th>Model</th>
          <th>Brand</th>
          <th>Year</th>
          <th>Color</th>
          <th>Plate</th>
          <th>Status</th>
          <th>Branch CNPJ</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for car in cars %}
        <tr class="hover">
          <td class="capitalize">{{ car.model }}</td>
          <td class="capitalize">{{ car.brand }}</td>
          <td class="capitalize">{{ car.year }}</td>
          <td class="capitalize">{{ car.color }}</td>
          <td class="capitalize">{{ car.plate }}</td>
          <td class="capitalize">{{ car.get_status_display }}</td>
          <td class="capitalize">{{ car.branch.cnpj }}</td>
          <td>
            <div>
              <div class="tooltip" data-tip="Details">
                <a href="{%url 'get_car_by_id' car_id=car.id %}" class="btn btn-square btn-sm">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#e0e0e0" viewBox="0 0 256 256">
                    <path
                      d="M247.31,124.76c-.35-.79-8.82-19.58-27.65-38.41C194.57,61.26,162.88,48,128,48S61.43,61.26,36.34,86.35C17.51,105.18,9,124,8.69,124.76a8,8,0,0,0,0,6.5c.35.79,8.82,19.57,27.65,38.4C61.43,194.74,93.12,208,128,208s66.57-13.26,91.66-38.34c18.83-18.83,27.3-37.61,27.65-38.4A8,8,0,0,0,247.31,124.76ZM128,192c-30.78,0-57.67-11.19-79.93-33.25A133.47,133.47,0,0,1,25,128,133.33,133.33,0,0,1,48.07,97.25C70.33,75.19,97.22,64,128,64s57.67,11.19,79.93,33.25A133.46,133.46,0,0,1,231.05,128C223.84,141.46,192.43,192,128,192Zm0-112a48,48,0,1,0,48,48A48.05,48.05,0,0,0,128,80Zm0,80a32,32,0,1,1,32-32A32,32,0,0,1,128,160Z"
                    ></path>
                  </svg>
                </a>
              </div>
              <div class="tooltip" data-tip="Remove">
                <a href="{%url 'delete_car_by_id' car_id=car.id %}" class="btn btn-square btn-sm btn-error" title="Remove">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#e0e0e0" viewBox="0 0 256 256">
                    <path
                      d="M216,48H40a8,8,0,0,0,0,16h8V208a16,16,0,0,0,16,16H192a16,16,0,0,0,16-16V64h8a8,8,0,0,0,0-16ZM192,208H64V64H192ZM80,24a8,8,0,0,1,8-8h80a8,8,0,0,1,0,16H88A8,8,0,0,1,80,24Z"
                    ></path>
                  </svg>
                </a>
              </div>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}